name: track_my_weight
description: "A Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  #icons_and_images
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1

  #localization
  intl: ^0.19.0

  #responsive
  flutter_screenutil: ^5.9.3

  #route
  auto_route: ^9.2.0

  #shared_preferences
  shared_preferences: ^2.3.2

  #toaster
  flutter_styled_toast: ^2.2.1

  #bloc
  flutter_bloc: ^8.1.6
  bloc_concurrency: ^0.2.5

  #notification
  flutter_local_notifications: ^17.2.3

  #json_model
  json_annotation: ^4.9.0

  #table_calendar
  table_calendar: ^3.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-100.ttf
          weight: 100
        - asset: assets/fonts/Roboto-300.ttf
          weight: 300
        - asset: assets/fonts/Roboto-400.ttf
          weight: 400
        - asset: assets/fonts/Roboto-500.ttf
          weight: 500
        - asset: assets/fonts/Roboto-700.ttf
          weight: 700
        - asset: assets/fonts/Roboto-900.ttf
          weight: 900

